import type { NextPage } from 'next'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import HeaderCompo from '../../component/index/headerCompo'
import FooterCompo from '../../component/index/footerCompo'
import { useRouter } from 'next/router'
import useCustomSWR from '../../utils/client/useCustumSWR'



const Admin: NextPage = (props) => {
    const router = useRouter()
    const { data, isLoading, isApiError, isServerError } = useCustomSWR("/api/admin/auth")
    if (isLoading) return <div>로딩중...</div>
    if (isServerError) {
        alert("서버 에러가 발생하였습니다")
        router.push("/")
    }
    if (isApiError) {
        alert("권한이 없습니다")
        router.push("/")
    }
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderCompo></HeaderCompo>
            <FooterCompo></FooterCompo>
        </div>
    )
}

export default Admin
