import type { NextPage } from 'next'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import HeaderCompo from '../../component/index/headerCompo'
import FooterCompo from '../../component/index/footerCompo'
import useCustomSWR from '../../utils/client/useCustumSWR'


const Productlist: NextPage = (props) => {
    const { data, isLoading, isError } = useCustomSWR("/api/admin/product")
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderCompo></HeaderCompo>
            <FooterCompo></FooterCompo>
        </div>
    )
}

export default Productlist