import type { NextPage } from 'next'
import Head from 'next/head'
import HeaderCompo from '../../component/index/headerCompo'
import FooterCompo from '../../component/index/footerCompo'
import UserTable from '../../component/admin/UserTable'
import { useRouter } from 'next/router'
import useCustomSWR from '../../utils/client/useCustumSWR'


const Userlist: NextPage = () => {
    const router = useRouter()
    const { data, isLoading, isApiError, isServerError } = useCustomSWR("/api/admin/userlist")
    if (isLoading) return <div>로딩중...</div>
    if (isServerError) {
        alert("서버 에러가 발생하였습니다")
        router.push("/")
    }
    if (isApiError) {
        alert("권한이 없습니다")
        router.push("/")
    }
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderCompo></HeaderCompo>
            <div className='container'>
                <UserTable>{data}</UserTable>
                <div className="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button type="button" className="btn btn-outline-success">권한부여</button>
                    <button type="button" className="btn btn-outline-warning">권한해제</button>
                    <button type="button" className="btn btn-outline-danger">회원삭제</button>
                </div>
            </div>
            <FooterCompo></FooterCompo>
        </div>
    )
}

export default Userlist
