import type { NextPage } from 'next'
import Head from 'next/head'
import HeaderCompo from '../../component/index/headerCompo'
import FooterCompo from '../../component/index/footerCompo'
import customAxios from '../../utils/customAxios'
import useSWR from 'swr'
import UserTable from '../../component/admin/UserTable'
import Router from 'next/router'


const Userlist: NextPage = () => {
    const fetcher = (url: string) => customAxios.get(url).then(res => res.data)
    const { data, error } = useSWR("/api/admin/userlist", fetcher)
    if (error) {
        alert("로그인이 필요합니다")
        Router.push("/login")
    }
    if (!data) return <div>loading...</div>
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderCompo></HeaderCompo>
            <UserTable>{data.result}</UserTable>
            <FooterCompo></FooterCompo>
        </div>
    )
}

export default Userlist
