import type { NextPage } from 'next'
import Head from 'next/head'
import HeaderCompo from '../../component/index/headerCompo'
import FooterCompo from '../../component/index/footerCompo'
import customAxios from '../../utils/customAxios'
import useSWR from 'swr'
import UserTable from '../../component/admin/UserTable'


const Userlist: NextPage = () => {
    const fetcher = async (url: string) => customAxios(url).then(res => res.data)
    const { data, error } = useSWR("/api/admin/userlist", fetcher)
    if (error) return <div>failed to load</div>
    if (!data) return <div>loading...</div>
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderCompo></HeaderCompo>
            <UserTable>{data.result}</UserTable>
            <FooterCompo></FooterCompo>
        </div>
    )
}

export default Userlist
