import type { NextPage } from 'next'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'

import MainBody from '../component/index/mainBody'
import HeaderCompo from '../component/index/headerCompo'
import FooterCompo from '../component/index/footerCompo'
import customAxios from '../utils/customAxios'
import useSWR from 'swr'


const Home: NextPage = () => {
  const fetcher = (url: string) => customAxios.get(url).then(res => res.data)
  const { data, error } = useSWR("/api/product/search?display=18&byCategory=true", fetcher)
  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <HeaderCompo></HeaderCompo>
      </header>

      <main>
        <MainBody {...data.result}></MainBody>
      </main>

      <footer>
        <FooterCompo></FooterCompo>
      </footer>

    </div>
  )
}

export default Home
