import type { NextPage } from 'next'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import MainBody from '../component/index/mainBody'
import HeaderCompo from '../component/index/headerCompo'
import FooterCompo from '../component/index/footerCompo'
import useCustomSWR from '../utils/client/useCustumSWR'


const Home: NextPage = () => {
  const { data, isLoading, isServerError } = useCustomSWR("/api/product/search?display=18&byCategory=true")
  if (isLoading) return <div>로딩중...</div>
  if (isServerError) {
    alert("서버 에러가 발생하였습니다")
  }
  if (!data) {
    alert("데이터베이스 에러가 발생하였습니다")
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <HeaderCompo></HeaderCompo>
      </header>

      <main>
        <MainBody {...data}></MainBody>
      </main>

      <footer>
        <FooterCompo></FooterCompo>
      </footer>

    </div>
  )
}

export default Home
